version: '2'
services:
    ocrapigateway2-elasticsearch:
        container_name: ocrapigateway2-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/OcrApiGateway2/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
